### ISSUE TITLE
v17 Not Bootable

### ISSUE THREAD

**Issue by sealsrock12** [thenickdude/KVM-Opencore#39]
I'm trying to boot it via a Proxmox machine on your guide, but it's unable to boot. In addition, I tried downloading it on a Windows 11 machine, extracted it with 7-Zip, and double-clicked it to mount it. It said that the image file is corrupt. Am I supposed to do something to extract it other than `gunzip` or 7-Zip?

**Comment by thenickdude** [comment]
I don't think Windows will know how to mount it so that's not surprising.

Most likely you've got secure boot enabled, which causes Proxmox to refuse to boot it. Remove and delete the EFI disk from the Hardware tab, then re-add one and be sure to un-tick "pre-enroll keys". This fixes the secure boot issue.

**Comment by sealsrock12** [comment]
Well, looks like I didn't read the instructions properly. I didn't remove `media=cdrom` from the IDE drives. Sorry for wasting your time.
