### ISSUE TITLE
Docker does not work

### ISSUE THREAD

**Issue by ChrisEngelhardt** [thenickdude/KVM-Opencore#4]
Docker does not work (unable to start docker machine).

In the Docker docs they say you can check if virtualization should work with “sysctl kern.hv_support” and that “… your CPU supports VT-x, VT-d, and VT-x with EPT (all three virtualization features must be supported)”.

Since docker runs in a vm (other than linux) and virtualization works (tested with virtual box and Parallels) I’m not quite sure where to look now. 

I've set cpu to host (Intel 9900K)

If I try to read trough the debug logs of docker. Think those are the cause of the problem

“msg=”com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 2099): stderr: 2020/10/23 10:47:15 WARN : hyperkit: failed to read stdout: EOF\n”

msg=”dial unix docker.raw.sock: connect: no such file or directory”

I`ve also tried a plain macOS installation but same results. Hope anyone can help.

**Comment by thenickdude** [comment]
It doesn't work for me either, and the cause isn't clear to me.

That error you show is because the hyperkit daemon doesn't start properly, so you're not very close to the root cause in the logs there. The root cause would be in the error logs from hyperkit.

Docker's diagnostics generate a big heap of logs which look good for sending off to Docker themselves...

**Comment by kholia** [comment]
https://github.com/kholia/OSX-KVM/blob/master/notes.md#running-docker-for-mac

I had it working a long time ago - not sure about the current status.

**Comment by ChrisEngelhardt** [comment]
ok seems the latests macOS version + the latest docker update fixed the issue :)

**Comment by thenickdude** [comment]
Ooh that's good news, thanks!
